/* Every country and its capital, with the capital's coordinates and time zone.
   Used to set "where you are" without needing a map pack installed, and to
   drive the sky, almanac and calendar for that place. Coordinates are the
   capital city to about a tenth of a degree — well inside the half-degree the
   sky is drawn to. Time zones are IANA names; a few large countries have more
   than one and the capital's zone is used. Facts, not opinions: no country is
   endorsed or recognised by being listed or not. */
window.CAPITALS = [
  // --- Europe ---
  { n: 'Albania', c: 'Tirana', lat: 41.33, lon: 19.82, tz: 'Europe/Tirane' },
  { n: 'Andorra', c: 'Andorra la Vella', lat: 42.51, lon: 1.52, tz: 'Europe/Andorra' },
  { n: 'Austria', c: 'Vienna', lat: 48.21, lon: 16.37, tz: 'Europe/Vienna' },
  { n: 'Belarus', c: 'Minsk', lat: 53.90, lon: 27.57, tz: 'Europe/Minsk' },
  { n: 'Belgium', c: 'Brussels', lat: 50.85, lon: 4.35, tz: 'Europe/Brussels' },
  { n: 'Bosnia and Herzegovina', c: 'Sarajevo', lat: 43.85, lon: 18.36, tz: 'Europe/Sarajevo' },
  { n: 'Bulgaria', c: 'Sofia', lat: 42.70, lon: 23.32, tz: 'Europe/Sofia' },
  { n: 'Croatia', c: 'Zagreb', lat: 45.81, lon: 15.98, tz: 'Europe/Zagreb' },
  { n: 'Cyprus', c: 'Nicosia', lat: 35.19, lon: 33.36, tz: 'Asia/Nicosia' },
  { n: 'Czechia', c: 'Prague', lat: 50.09, lon: 14.42, tz: 'Europe/Prague' },
  { n: 'Denmark', c: 'Copenhagen', lat: 55.68, lon: 12.57, tz: 'Europe/Copenhagen' },
  { n: 'Estonia', c: 'Tallinn', lat: 59.44, lon: 24.75, tz: 'Europe/Tallinn' },
  { n: 'Finland', c: 'Helsinki', lat: 60.17, lon: 24.94, tz: 'Europe/Helsinki' },
  { n: 'France', c: 'Paris', lat: 48.85, lon: 2.35, tz: 'Europe/Paris' },
  { n: 'Germany', c: 'Berlin', lat: 52.52, lon: 13.40, tz: 'Europe/Berlin' },
  { n: 'Greece', c: 'Athens', lat: 37.98, lon: 23.73, tz: 'Europe/Athens' },
  { n: 'Hungary', c: 'Budapest', lat: 47.50, lon: 19.04, tz: 'Europe/Budapest' },
  { n: 'Iceland', c: 'Reykjavik', lat: 64.15, lon: -21.94, tz: 'Atlantic/Reykjavik' },
  { n: 'Ireland', c: 'Dublin', lat: 53.35, lon: -6.26, tz: 'Europe/Dublin' },
  { n: 'Italy', c: 'Rome', lat: 41.90, lon: 12.50, tz: 'Europe/Rome' },
  { n: 'Kosovo', c: 'Pristina', lat: 42.66, lon: 21.17, tz: 'Europe/Belgrade' },
  { n: 'Latvia', c: 'Riga', lat: 56.95, lon: 24.11, tz: 'Europe/Riga' },
  { n: 'Liechtenstein', c: 'Vaduz', lat: 47.14, lon: 9.52, tz: 'Europe/Vaduz' },
  { n: 'Lithuania', c: 'Vilnius', lat: 54.69, lon: 25.28, tz: 'Europe/Vilnius' },
  { n: 'Luxembourg', c: 'Luxembourg', lat: 49.61, lon: 6.13, tz: 'Europe/Luxembourg' },
  { n: 'Malta', c: 'Valletta', lat: 35.90, lon: 14.51, tz: 'Europe/Malta' },
  { n: 'Moldova', c: 'Chisinau', lat: 47.01, lon: 28.86, tz: 'Europe/Chisinau' },
  { n: 'Monaco', c: 'Monaco', lat: 43.74, lon: 7.42, tz: 'Europe/Monaco' },
  { n: 'Montenegro', c: 'Podgorica', lat: 42.44, lon: 19.26, tz: 'Europe/Podgorica' },
  { n: 'Netherlands', c: 'Amsterdam', lat: 52.37, lon: 4.90, tz: 'Europe/Amsterdam' },
  { n: 'North Macedonia', c: 'Skopje', lat: 41.99, lon: 21.43, tz: 'Europe/Skopje' },
  { n: 'Norway', c: 'Oslo', lat: 59.91, lon: 10.75, tz: 'Europe/Oslo' },
  { n: 'Poland', c: 'Warsaw', lat: 52.23, lon: 21.01, tz: 'Europe/Warsaw' },
  { n: 'Portugal', c: 'Lisbon', lat: 38.72, lon: -9.14, tz: 'Europe/Lisbon' },
  { n: 'Romania', c: 'Bucharest', lat: 44.43, lon: 26.10, tz: 'Europe/Bucharest' },
  { n: 'Russia', c: 'Moscow', lat: 55.76, lon: 37.62, tz: 'Europe/Moscow' },
  { n: 'San Marino', c: 'San Marino', lat: 43.94, lon: 12.45, tz: 'Europe/Rome' },
  { n: 'Serbia', c: 'Belgrade', lat: 44.79, lon: 20.45, tz: 'Europe/Belgrade' },
  { n: 'Slovakia', c: 'Bratislava', lat: 48.15, lon: 17.11, tz: 'Europe/Bratislava' },
  { n: 'Slovenia', c: 'Ljubljana', lat: 46.06, lon: 14.51, tz: 'Europe/Ljubljana' },
  { n: 'Spain', c: 'Madrid', lat: 40.42, lon: -3.70, tz: 'Europe/Madrid' },
  { n: 'Sweden', c: 'Stockholm', lat: 59.33, lon: 18.07, tz: 'Europe/Stockholm' },
  { n: 'Switzerland', c: 'Bern', lat: 46.95, lon: 7.45, tz: 'Europe/Zurich' },
  { n: 'Ukraine', c: 'Kyiv', lat: 50.45, lon: 30.52, tz: 'Europe/Kyiv' },
  { n: 'United Kingdom', c: 'London', lat: 51.51, lon: -0.13, tz: 'Europe/London' },
  { n: 'Vatican City', c: 'Vatican City', lat: 41.90, lon: 12.45, tz: 'Europe/Rome' },
  // --- Asia ---
  { n: 'Afghanistan', c: 'Kabul', lat: 34.53, lon: 69.17, tz: 'Asia/Kabul' },
  { n: 'Armenia', c: 'Yerevan', lat: 40.18, lon: 44.51, tz: 'Asia/Yerevan' },
  { n: 'Azerbaijan', c: 'Baku', lat: 40.41, lon: 49.87, tz: 'Asia/Baku' },
  { n: 'Bahrain', c: 'Manama', lat: 26.23, lon: 50.59, tz: 'Asia/Bahrain' },
  { n: 'Bangladesh', c: 'Dhaka', lat: 23.81, lon: 90.41, tz: 'Asia/Dhaka' },
  { n: 'Bhutan', c: 'Thimphu', lat: 27.47, lon: 89.64, tz: 'Asia/Thimphu' },
  { n: 'Brunei', c: 'Bandar Seri Begawan', lat: 4.89, lon: 114.94, tz: 'Asia/Brunei' },
  { n: 'Cambodia', c: 'Phnom Penh', lat: 11.56, lon: 104.92, tz: 'Asia/Phnom_Penh' },
  { n: 'China', c: 'Beijing', lat: 39.90, lon: 116.41, tz: 'Asia/Shanghai' },
  { n: 'Georgia', c: 'Tbilisi', lat: 41.72, lon: 44.83, tz: 'Asia/Tbilisi' },
  { n: 'India', c: 'New Delhi', lat: 28.61, lon: 77.21, tz: 'Asia/Kolkata' },
  { n: 'Indonesia', c: 'Jakarta', lat: -6.21, lon: 106.85, tz: 'Asia/Jakarta' },
  { n: 'Iran', c: 'Tehran', lat: 35.69, lon: 51.39, tz: 'Asia/Tehran' },
  { n: 'Iraq', c: 'Baghdad', lat: 33.32, lon: 44.36, tz: 'Asia/Baghdad' },
  { n: 'Israel', c: 'Jerusalem', lat: 31.77, lon: 35.21, tz: 'Asia/Jerusalem' },
  { n: 'Japan', c: 'Tokyo', lat: 35.68, lon: 139.69, tz: 'Asia/Tokyo' },
  { n: 'Jordan', c: 'Amman', lat: 31.95, lon: 35.93, tz: 'Asia/Amman' },
  { n: 'Kazakhstan', c: 'Astana', lat: 51.17, lon: 71.43, tz: 'Asia/Almaty' },
  { n: 'Kuwait', c: 'Kuwait City', lat: 29.38, lon: 47.99, tz: 'Asia/Kuwait' },
  { n: 'Kyrgyzstan', c: 'Bishkek', lat: 42.87, lon: 74.59, tz: 'Asia/Bishkek' },
  { n: 'Laos', c: 'Vientiane', lat: 17.97, lon: 102.60, tz: 'Asia/Vientiane' },
  { n: 'Lebanon', c: 'Beirut', lat: 33.89, lon: 35.50, tz: 'Asia/Beirut' },
  { n: 'Malaysia', c: 'Kuala Lumpur', lat: 3.14, lon: 101.69, tz: 'Asia/Kuala_Lumpur' },
  { n: 'Maldives', c: 'Male', lat: 4.18, lon: 73.51, tz: 'Indian/Maldives' },
  { n: 'Mongolia', c: 'Ulaanbaatar', lat: 47.89, lon: 106.91, tz: 'Asia/Ulaanbaatar' },
  { n: 'Myanmar', c: 'Naypyidaw', lat: 19.76, lon: 96.08, tz: 'Asia/Yangon' },
  { n: 'Nepal', c: 'Kathmandu', lat: 27.72, lon: 85.32, tz: 'Asia/Kathmandu' },
  { n: 'North Korea', c: 'Pyongyang', lat: 39.04, lon: 125.76, tz: 'Asia/Pyongyang' },
  { n: 'Oman', c: 'Muscat', lat: 23.59, lon: 58.41, tz: 'Asia/Muscat' },
  { n: 'Pakistan', c: 'Islamabad', lat: 33.68, lon: 73.05, tz: 'Asia/Karachi' },
  { n: 'Palestine', c: 'Ramallah', lat: 31.90, lon: 35.20, tz: 'Asia/Hebron' },
  { n: 'Philippines', c: 'Manila', lat: 14.60, lon: 120.98, tz: 'Asia/Manila' },
  { n: 'Qatar', c: 'Doha', lat: 25.29, lon: 51.53, tz: 'Asia/Qatar' },
  { n: 'Saudi Arabia', c: 'Riyadh', lat: 24.71, lon: 46.68, tz: 'Asia/Riyadh' },
  { n: 'Singapore', c: 'Singapore', lat: 1.35, lon: 103.82, tz: 'Asia/Singapore' },
  { n: 'South Korea', c: 'Seoul', lat: 37.57, lon: 126.98, tz: 'Asia/Seoul' },
  { n: 'Sri Lanka', c: 'Colombo', lat: 6.93, lon: 79.86, tz: 'Asia/Colombo' },
  { n: 'Syria', c: 'Damascus', lat: 33.51, lon: 36.29, tz: 'Asia/Damascus' },
  { n: 'Taiwan', c: 'Taipei', lat: 25.03, lon: 121.57, tz: 'Asia/Taipei' },
  { n: 'Tajikistan', c: 'Dushanbe', lat: 38.56, lon: 68.79, tz: 'Asia/Dushanbe' },
  { n: 'Thailand', c: 'Bangkok', lat: 13.76, lon: 100.50, tz: 'Asia/Bangkok' },
  { n: 'Timor-Leste', c: 'Dili', lat: -8.56, lon: 125.56, tz: 'Asia/Dili' },
  { n: 'Turkey', c: 'Ankara', lat: 39.93, lon: 32.86, tz: 'Europe/Istanbul' },
  { n: 'Turkmenistan', c: 'Ashgabat', lat: 37.96, lon: 58.33, tz: 'Asia/Ashgabat' },
  { n: 'United Arab Emirates', c: 'Abu Dhabi', lat: 24.45, lon: 54.38, tz: 'Asia/Dubai' },
  { n: 'Uzbekistan', c: 'Tashkent', lat: 41.30, lon: 69.24, tz: 'Asia/Tashkent' },
  { n: 'Vietnam', c: 'Hanoi', lat: 21.03, lon: 105.85, tz: 'Asia/Ho_Chi_Minh' },
  { n: 'Yemen', c: 'Sanaa', lat: 15.35, lon: 44.21, tz: 'Asia/Aden' },
  // --- Africa ---
  { n: 'Algeria', c: 'Algiers', lat: 36.75, lon: 3.06, tz: 'Africa/Algiers' },
  { n: 'Angola', c: 'Luanda', lat: -8.84, lon: 13.23, tz: 'Africa/Luanda' },
  { n: 'Benin', c: 'Porto-Novo', lat: 6.50, lon: 2.63, tz: 'Africa/Porto-Novo' },
  { n: 'Botswana', c: 'Gaborone', lat: -24.66, lon: 25.91, tz: 'Africa/Gaborone' },
  { n: 'Burkina Faso', c: 'Ouagadougou', lat: 12.37, lon: -1.53, tz: 'Africa/Ouagadougou' },
  { n: 'Burundi', c: 'Gitega', lat: -3.43, lon: 29.93, tz: 'Africa/Bujumbura' },
  { n: 'Cameroon', c: 'Yaounde', lat: 3.85, lon: 11.50, tz: 'Africa/Douala' },
  { n: 'Cape Verde', c: 'Praia', lat: 14.93, lon: -23.51, tz: 'Atlantic/Cape_Verde' },
  { n: 'Central African Republic', c: 'Bangui', lat: 4.39, lon: 18.56, tz: 'Africa/Bangui' },
  { n: 'Chad', c: "N'Djamena", lat: 12.11, lon: 15.04, tz: 'Africa/Ndjamena' },
  { n: 'Comoros', c: 'Moroni', lat: -11.70, lon: 43.26, tz: 'Indian/Comoro' },
  { n: 'Congo (Brazzaville)', c: 'Brazzaville', lat: -4.27, lon: 15.28, tz: 'Africa/Brazzaville' },
  { n: 'Congo (Kinshasa)', c: 'Kinshasa', lat: -4.32, lon: 15.31, tz: 'Africa/Kinshasa' },
  { n: "Cote d'Ivoire", c: 'Yamoussoukro', lat: 6.83, lon: -5.29, tz: 'Africa/Abidjan' },
  { n: 'Djibouti', c: 'Djibouti', lat: 11.59, lon: 43.15, tz: 'Africa/Djibouti' },
  { n: 'Egypt', c: 'Cairo', lat: 30.04, lon: 31.24, tz: 'Africa/Cairo' },
  { n: 'Equatorial Guinea', c: 'Malabo', lat: 3.75, lon: 8.78, tz: 'Africa/Malabo' },
  { n: 'Eritrea', c: 'Asmara', lat: 15.34, lon: 38.93, tz: 'Africa/Asmara' },
  { n: 'Eswatini', c: 'Mbabane', lat: -26.32, lon: 31.14, tz: 'Africa/Mbabane' },
  { n: 'Ethiopia', c: 'Addis Ababa', lat: 9.03, lon: 38.74, tz: 'Africa/Addis_Ababa' },
  { n: 'Gabon', c: 'Libreville', lat: 0.42, lon: 9.47, tz: 'Africa/Libreville' },
  { n: 'Gambia', c: 'Banjul', lat: 13.45, lon: -16.58, tz: 'Africa/Banjul' },
  { n: 'Ghana', c: 'Accra', lat: 5.60, lon: -0.19, tz: 'Africa/Accra' },
  { n: 'Guinea', c: 'Conakry', lat: 9.51, lon: -13.71, tz: 'Africa/Conakry' },
  { n: 'Guinea-Bissau', c: 'Bissau', lat: 11.86, lon: -15.60, tz: 'Africa/Bissau' },
  { n: 'Kenya', c: 'Nairobi', lat: -1.29, lon: 36.82, tz: 'Africa/Nairobi' },
  { n: 'Lesotho', c: 'Maseru', lat: -29.31, lon: 27.48, tz: 'Africa/Maseru' },
  { n: 'Liberia', c: 'Monrovia', lat: 6.30, lon: -10.80, tz: 'Africa/Monrovia' },
  { n: 'Libya', c: 'Tripoli', lat: 32.89, lon: 13.19, tz: 'Africa/Tripoli' },
  { n: 'Madagascar', c: 'Antananarivo', lat: -18.88, lon: 47.51, tz: 'Indian/Antananarivo' },
  { n: 'Malawi', c: 'Lilongwe', lat: -13.96, lon: 33.79, tz: 'Africa/Blantyre' },
  { n: 'Mali', c: 'Bamako', lat: 12.64, lon: -8.00, tz: 'Africa/Bamako' },
  { n: 'Mauritania', c: 'Nouakchott', lat: 18.08, lon: -15.98, tz: 'Africa/Nouakchott' },
  { n: 'Mauritius', c: 'Port Louis', lat: -20.16, lon: 57.50, tz: 'Indian/Mauritius' },
  { n: 'Morocco', c: 'Rabat', lat: 34.02, lon: -6.83, tz: 'Africa/Casablanca' },
  { n: 'Mozambique', c: 'Maputo', lat: -25.97, lon: 32.57, tz: 'Africa/Maputo' },
  { n: 'Namibia', c: 'Windhoek', lat: -22.56, lon: 17.08, tz: 'Africa/Windhoek' },
  { n: 'Niger', c: 'Niamey', lat: 13.51, lon: 2.11, tz: 'Africa/Niamey' },
  { n: 'Nigeria', c: 'Abuja', lat: 9.08, lon: 7.40, tz: 'Africa/Lagos' },
  { n: 'Rwanda', c: 'Kigali', lat: -1.94, lon: 30.06, tz: 'Africa/Kigali' },
  { n: 'Sao Tome and Principe', c: 'Sao Tome', lat: 0.34, lon: 6.73, tz: 'Africa/Sao_Tome' },
  { n: 'Senegal', c: 'Dakar', lat: 14.72, lon: -17.47, tz: 'Africa/Dakar' },
  { n: 'Seychelles', c: 'Victoria', lat: -4.62, lon: 55.45, tz: 'Indian/Mahe' },
  { n: 'Sierra Leone', c: 'Freetown', lat: 8.48, lon: -13.23, tz: 'Africa/Freetown' },
  { n: 'Somalia', c: 'Mogadishu', lat: 2.05, lon: 45.32, tz: 'Africa/Mogadishu' },
  { n: 'South Africa', c: 'Pretoria', lat: -25.75, lon: 28.19, tz: 'Africa/Johannesburg' },
  { n: 'South Sudan', c: 'Juba', lat: 4.85, lon: 31.58, tz: 'Africa/Juba' },
  { n: 'Sudan', c: 'Khartoum', lat: 15.50, lon: 32.56, tz: 'Africa/Khartoum' },
  { n: 'Tanzania', c: 'Dodoma', lat: -6.16, lon: 35.75, tz: 'Africa/Dar_es_Salaam' },
  { n: 'Togo', c: 'Lome', lat: 6.13, lon: 1.22, tz: 'Africa/Lome' },
  { n: 'Tunisia', c: 'Tunis', lat: 36.81, lon: 10.18, tz: 'Africa/Tunis' },
  { n: 'Uganda', c: 'Kampala', lat: 0.35, lon: 32.58, tz: 'Africa/Kampala' },
  { n: 'Zambia', c: 'Lusaka', lat: -15.42, lon: 28.28, tz: 'Africa/Lusaka' },
  { n: 'Zimbabwe', c: 'Harare', lat: -17.83, lon: 31.05, tz: 'Africa/Harare' },
  // --- Americas ---
  { n: 'Antigua and Barbuda', c: "St. John's", lat: 17.12, lon: -61.85, tz: 'America/Antigua' },
  { n: 'Argentina', c: 'Buenos Aires', lat: -34.60, lon: -58.38, tz: 'America/Argentina/Buenos_Aires' },
  { n: 'Bahamas', c: 'Nassau', lat: 25.06, lon: -77.35, tz: 'America/Nassau' },
  { n: 'Barbados', c: 'Bridgetown', lat: 13.11, lon: -59.62, tz: 'America/Barbados' },
  { n: 'Belize', c: 'Belmopan', lat: 17.25, lon: -88.77, tz: 'America/Belize' },
  { n: 'Bolivia', c: 'La Paz', lat: -16.50, lon: -68.15, tz: 'America/La_Paz' },
  { n: 'Brazil', c: 'Brasilia', lat: -15.79, lon: -47.88, tz: 'America/Sao_Paulo' },
  { n: 'Canada', c: 'Ottawa', lat: 45.42, lon: -75.70, tz: 'America/Toronto' },
  { n: 'Chile', c: 'Santiago', lat: -33.45, lon: -70.67, tz: 'America/Santiago' },
  { n: 'Colombia', c: 'Bogota', lat: 4.71, lon: -74.07, tz: 'America/Bogota' },
  { n: 'Costa Rica', c: 'San Jose', lat: 9.93, lon: -84.08, tz: 'America/Costa_Rica' },
  { n: 'Cuba', c: 'Havana', lat: 23.11, lon: -82.37, tz: 'America/Havana' },
  { n: 'Dominica', c: 'Roseau', lat: 15.30, lon: -61.39, tz: 'America/Dominica' },
  { n: 'Dominican Republic', c: 'Santo Domingo', lat: 18.49, lon: -69.93, tz: 'America/Santo_Domingo' },
  { n: 'Ecuador', c: 'Quito', lat: -0.18, lon: -78.47, tz: 'America/Guayaquil' },
  { n: 'El Salvador', c: 'San Salvador', lat: 13.69, lon: -89.22, tz: 'America/El_Salvador' },
  { n: 'Grenada', c: "St. George's", lat: 12.06, lon: -61.75, tz: 'America/Grenada' },
  { n: 'Guatemala', c: 'Guatemala City', lat: 14.63, lon: -90.51, tz: 'America/Guatemala' },
  { n: 'Guyana', c: 'Georgetown', lat: 6.80, lon: -58.16, tz: 'America/Guyana' },
  { n: 'Haiti', c: 'Port-au-Prince', lat: 18.55, lon: -72.34, tz: 'America/Port-au-Prince' },
  { n: 'Honduras', c: 'Tegucigalpa', lat: 14.07, lon: -87.19, tz: 'America/Tegucigalpa' },
  { n: 'Jamaica', c: 'Kingston', lat: 18.02, lon: -76.79, tz: 'America/Jamaica' },
  { n: 'Mexico', c: 'Mexico City', lat: 19.43, lon: -99.13, tz: 'America/Mexico_City' },
  { n: 'Nicaragua', c: 'Managua', lat: 12.11, lon: -86.27, tz: 'America/Managua' },
  { n: 'Panama', c: 'Panama City', lat: 8.98, lon: -79.52, tz: 'America/Panama' },
  { n: 'Paraguay', c: 'Asuncion', lat: -25.28, lon: -57.64, tz: 'America/Asuncion' },
  { n: 'Peru', c: 'Lima', lat: -12.05, lon: -77.04, tz: 'America/Lima' },
  { n: 'Saint Kitts and Nevis', c: 'Basseterre', lat: 17.30, lon: -62.72, tz: 'America/St_Kitts' },
  { n: 'Saint Lucia', c: 'Castries', lat: 14.01, lon: -60.99, tz: 'America/St_Lucia' },
  { n: 'Saint Vincent and the Grenadines', c: 'Kingstown', lat: 13.16, lon: -61.22, tz: 'America/St_Vincent' },
  { n: 'Suriname', c: 'Paramaribo', lat: 5.87, lon: -55.17, tz: 'America/Paramaribo' },
  { n: 'Trinidad and Tobago', c: 'Port of Spain', lat: 10.66, lon: -61.52, tz: 'America/Port_of_Spain' },
  { n: 'United States', c: 'Washington, D.C.', lat: 38.90, lon: -77.04, tz: 'America/New_York' },
  { n: 'Uruguay', c: 'Montevideo', lat: -34.90, lon: -56.16, tz: 'America/Montevideo' },
  { n: 'Venezuela', c: 'Caracas', lat: 10.49, lon: -66.88, tz: 'America/Caracas' },
  // --- Oceania ---
  { n: 'Australia', c: 'Canberra', lat: -35.28, lon: 149.13, tz: 'Australia/Sydney' },
  { n: 'Fiji', c: 'Suva', lat: -18.14, lon: 178.44, tz: 'Pacific/Fiji' },
  { n: 'Kiribati', c: 'Tarawa', lat: 1.33, lon: 172.98, tz: 'Pacific/Tarawa' },
  { n: 'Marshall Islands', c: 'Majuro', lat: 7.09, lon: 171.38, tz: 'Pacific/Majuro' },
  { n: 'Micronesia', c: 'Palikir', lat: 6.92, lon: 158.16, tz: 'Pacific/Pohnpei' },
  { n: 'Nauru', c: 'Yaren', lat: -0.55, lon: 166.92, tz: 'Pacific/Nauru' },
  { n: 'New Zealand', c: 'Wellington', lat: -41.29, lon: 174.78, tz: 'Pacific/Auckland' },
  { n: 'Palau', c: 'Ngerulmud', lat: 7.50, lon: 134.62, tz: 'Pacific/Palau' },
  { n: 'Papua New Guinea', c: 'Port Moresby', lat: -9.44, lon: 147.18, tz: 'Pacific/Port_Moresby' },
  { n: 'Samoa', c: 'Apia', lat: -13.83, lon: -171.77, tz: 'Pacific/Apia' },
  { n: 'Solomon Islands', c: 'Honiara', lat: -9.43, lon: 159.96, tz: 'Pacific/Guadalcanal' },
  { n: 'Tonga', c: "Nuku'alofa", lat: -21.14, lon: -175.20, tz: 'Pacific/Tongatapu' },
  { n: 'Tuvalu', c: 'Funafuti', lat: -8.52, lon: 179.20, tz: 'Pacific/Funafuti' },
  { n: 'Vanuatu', c: 'Port Vila', lat: -17.73, lon: 168.32, tz: 'Pacific/Efate' },
];
