'use strict';
/* The periodic table. Number, symbol, name, standard atomic weight (a bracket
   is the mass number of the longest-lived isotope), category, group, period,
   state at room temperature, and a line on what it is or does. */

const ELEMENT_CATEGORIES = {
  alkali: 'Alkali metal', alkaline: 'Alkaline earth metal', transition: 'Transition metal',
  post: 'Post-transition metal', metalloid: 'Metalloid', nonmetal: 'Nonmetal', halogen: 'Halogen',
  noble: 'Noble gas', lanthanide: 'Lanthanide', actinide: 'Actinide', unknown: 'Unknown properties',
};

// [Z, symbol, name, mass, category, group, period, state, note]
const ELEMENTS = [
  [1, 'H', 'Hydrogen', '1.008', 'nonmetal', 1, 1, 'gas', 'The lightest and most common element in the universe. Two of them and one oxygen make water. Burns cleanly; the fuel of the sun.'],
  [2, 'He', 'Helium', '4.003', 'noble', 18, 1, 'gas', 'Second lightest, will not burn or react with anything. Lifts balloons and airships; cools the strongest magnets.'],
  [3, 'Li', 'Lithium', '6.94', 'alkali', 1, 2, 'solid', 'Lightest metal; floats on oil. The heart of rechargeable batteries. Reacts with water.'],
  [4, 'Be', 'Beryllium', '9.012', 'alkaline', 2, 2, 'solid', 'Light, stiff, poisonous dust. Springs, X-ray windows, spacecraft.'],
  [5, 'B', 'Boron', '10.81', 'metalloid', 13, 2, 'solid', 'In borax and boric acid — a mild antiseptic, a flux for soldering, a wood preservative, an insecticide.'],
  [6, 'C', 'Carbon', '12.011', 'nonmetal', 14, 2, 'solid', 'The element of life: every living thing is built on chains of it. Coal, charcoal, diamond, graphite, soot. Charcoal filters water and makes steel.'],
  [7, 'N', 'Nitrogen', '14.007', 'nonmetal', 15, 2, 'gas', 'Four-fifths of the air. Plants need it fixed in the soil — that is what manure, legumes and lightning provide. In every protein.'],
  [8, 'O', 'Oxygen', '15.999', 'nonmetal', 16, 2, 'gas', 'A fifth of the air; what burning and breathing consume. Half the weight of the rocks, most of the weight of water.'],
  [9, 'F', 'Fluorine', '18.998', 'halogen', 17, 2, 'gas', 'The most reactive element of all. In toothpaste as fluoride, in non-stick pans, in refrigerants.'],
  [10, 'Ne', 'Neon', '20.180', 'noble', 18, 2, 'gas', 'Glows orange-red in a tube. Otherwise does nothing at all.'],
  [11, 'Na', 'Sodium', '22.990', 'alkali', 1, 3, 'solid', 'Soft metal that bursts into flame in water. As sodium chloride it is salt: what preserves food, and what the body cannot live without.'],
  [12, 'Mg', 'Magnesium', '24.305', 'alkaline', 2, 3, 'solid', 'Light metal that burns with a blinding white light — fire starters and flares. At the centre of every chlorophyll molecule.'],
  [13, 'Al', 'Aluminium', '26.982', 'post', 13, 3, 'solid', 'Light, does not rust, conducts well. Most common metal in the crust but locked in clay; cheap only with electricity. Pans, foil, cans, aircraft.'],
  [14, 'Si', 'Silicon', '28.085', 'metalloid', 14, 3, 'solid', 'Sand, quartz, glass, and most rocks. Purified, the material of every computer chip and solar panel.'],
  [15, 'P', 'Phosphorus', '30.974', 'nonmetal', 15, 3, 'solid', 'Essential for every cell and for bones. Plants need it; bone meal and manure supply it. White phosphorus catches fire in air; red is the match-striker.'],
  [16, 'S', 'Sulfur', '32.06', 'nonmetal', 16, 3, 'solid', 'Yellow, found pure near volcanoes. Gunpowder, matches, vulcanised rubber, sulfuric acid, a fungicide on vines. Smells of rotten eggs as a gas.'],
  [17, 'Cl', 'Chlorine', '35.45', 'halogen', 17, 3, 'gas', 'Poisonous green gas; as bleach and in tiny doses it makes water safe to drink. The other half of salt.'],
  [18, 'Ar', 'Argon', '39.948', 'noble', 18, 3, 'gas', 'One per cent of the air, entirely inert. Fills light bulbs and shields welding.'],
  [19, 'K', 'Potassium', '39.098', 'alkali', 1, 4, 'solid', 'Reacts violently with water. Potash, from wood ash, is the K in fertiliser and in soap-making. Bananas, and every nerve, depend on it.'],
  [20, 'Ca', 'Calcium', '40.078', 'alkaline', 2, 4, 'solid', 'Bones, teeth, shells, chalk, limestone, marble. Burn limestone for quicklime: mortar, plaster, and sweetening sour soil.'],
  [21, 'Sc', 'Scandium', '44.956', 'transition', 3, 4, 'solid', 'Rare, light; strengthens aluminium in bicycle frames and aircraft.'],
  [22, 'Ti', 'Titanium', '47.867', 'transition', 4, 4, 'solid', 'Strong as steel at half the weight, and never corrodes. Hip joints, aircraft, white paint (as the oxide).'],
  [23, 'V', 'Vanadium', '50.942', 'transition', 5, 4, 'solid', 'A little of it makes steel tough: spanners, springs, engine parts.'],
  [24, 'Cr', 'Chromium', '51.996', 'transition', 6, 4, 'solid', 'Hard, bright, does not tarnish. Stainless steel is steel with a tenth of chromium; chrome plating.'],
  [25, 'Mn', 'Manganese', '54.938', 'transition', 7, 4, 'solid', 'Essential in steel-making, and a trace nutrient. In dry-cell batteries.'],
  [26, 'Fe', 'Iron', '55.845', 'transition', 8, 4, 'solid', 'The metal of tools, nails, engines and bridges; with carbon, steel. Rusts. Carries oxygen in your blood. Smelted from ore with charcoal.'],
  [27, 'Co', 'Cobalt', '58.933', 'transition', 9, 4, 'solid', 'Blue glass and glaze; magnets; batteries. Part of vitamin B12.'],
  [28, 'Ni', 'Nickel', '58.693', 'transition', 10, 4, 'solid', 'Does not rust; coins, stainless steel, batteries, plating.'],
  [29, 'Cu', 'Copper', '63.546', 'transition', 11, 4, 'solid', 'Conducts electricity and heat better than anything but silver. Wire, pipes, pans, coins. Kills germs on contact. With tin makes bronze; with zinc, brass.'],
  [30, 'Zn', 'Zinc', '65.38', 'transition', 12, 4, 'solid', 'Galvanising: a coat of zinc keeps steel from rusting. Brass, batteries, ointment, a nutrient.'],
  [31, 'Ga', 'Gallium', '69.723', 'post', 13, 4, 'solid', 'Melts in your hand. LEDs and fast electronics.'],
  [32, 'Ge', 'Germanium', '72.630', 'metalloid', 14, 4, 'solid', 'The first transistors were germanium. Infrared optics.'],
  [33, 'As', 'Arsenic', '74.922', 'metalloid', 15, 4, 'solid', 'The classic poison. Once in wood preservative, pesticides and green paint; in some well water — test it.'],
  [34, 'Se', 'Selenium', '78.971', 'nonmetal', 16, 4, 'solid', 'A trace nutrient; toxic in more than a trace. Photocells, glass.'],
  [35, 'Br', 'Bromine', '79.904', 'halogen', 17, 4, 'liquid', 'One of two elements liquid at room temperature; red-brown, fuming, corrosive. Flame retardants, pool disinfectant.'],
  [36, 'Kr', 'Krypton', '83.798', 'noble', 18, 4, 'gas', 'Inert; in some bulbs and lasers.'],
  [37, 'Rb', 'Rubidium', '85.468', 'alkali', 1, 5, 'solid', 'Soft, reactive, catches fire in air. Atomic clocks.'],
  [38, 'Sr', 'Strontium', '87.62', 'alkaline', 2, 5, 'solid', 'Burns crimson — red fireworks and flares. Behaves like calcium in bone.'],
  [39, 'Y', 'Yttrium', '88.906', 'transition', 3, 5, 'solid', 'Red phosphor in old televisions; lasers; strengthens alloys.'],
  [40, 'Zr', 'Zirconium', '91.224', 'transition', 4, 5, 'solid', 'Corrosion-proof; cladding for nuclear fuel. Cubic zirconia imitates diamond.'],
  [41, 'Nb', 'Niobium', '92.906', 'transition', 5, 5, 'solid', 'Superconducting magnets, jet engines, jewellery that does not react with skin.'],
  [42, 'Mo', 'Molybdenum', '95.95', 'transition', 6, 5, 'solid', 'Toughens steel for high temperatures; a plant micronutrient; a dry lubricant.'],
  [43, 'Tc', 'Technetium', '[98]', 'transition', 7, 5, 'solid', 'The lightest element with no stable form; made, not mined. Medical imaging.'],
  [44, 'Ru', 'Ruthenium', '101.07', 'transition', 8, 5, 'solid', 'Hardens platinum; electrical contacts; catalysts.'],
  [45, 'Rh', 'Rhodium', '102.91', 'transition', 9, 5, 'solid', 'The most expensive metal, in catalytic converters.'],
  [46, 'Pd', 'Palladium', '106.42', 'transition', 10, 5, 'solid', 'Catalytic converters, dentistry, hydrogen storage.'],
  [47, 'Ag', 'Silver', '107.87', 'transition', 11, 5, 'solid', 'Best conductor of all; tarnishes black with sulfur. Coins, mirrors, photography, and it kills bacteria — silver in a water filter.'],
  [48, 'Cd', 'Cadmium', '112.41', 'transition', 12, 5, 'solid', 'Poisonous; old batteries and yellow pigment. Do not burn or melt scrap that contains it.'],
  [49, 'In', 'Indium', '114.82', 'post', 13, 5, 'solid', 'The transparent conductor on touchscreens; soft solders.'],
  [50, 'Sn', 'Tin', '118.71', 'post', 14, 5, 'solid', 'Does not rust: the lining of tin cans, the tin in bronze and pewter, the metal in solder. Cornwall was mined for it for 4,000 years.'],
  [51, 'Sb', 'Antimony', '121.76', 'metalloid', 15, 5, 'solid', 'Hardens lead for bullets and type; flame retardants. Poisonous.'],
  [52, 'Te', 'Tellurium', '127.60', 'metalloid', 16, 5, 'solid', 'Rare; solar panels and alloys. Gives garlic breath.'],
  [53, 'I', 'Iodine', '126.90', 'halogen', 17, 5, 'solid', 'Purple-black crystals that turn to violet vapour. Tincture of iodine disinfects wounds; tablets purify water; the thyroid needs it, seaweed has it.'],
  [54, 'Xe', 'Xenon', '131.29', 'noble', 18, 5, 'gas', 'Inert; bright white lamps, an anaesthetic, ion-engine propellant.'],
  [55, 'Cs', 'Caesium', '132.91', 'alkali', 1, 6, 'solid', 'Melts just above room temperature, explodes in water. The atomic clock that defines the second.'],
  [56, 'Ba', 'Barium', '137.33', 'alkaline', 2, 6, 'solid', 'Green fireworks; the "barium meal" that shows up on X-rays; drilling mud.'],
  [57, 'La', 'Lanthanum', '138.91', 'lanthanide', 3, 6, 'solid', 'Camera lenses, battery electrodes, lighter flints (with cerium).'],
  [58, 'Ce', 'Cerium', '140.12', 'lanthanide', 3, 6, 'solid', 'Most common rare earth. Lighter flints spark because of it; glass polishing; self-cleaning ovens.'],
  [59, 'Pr', 'Praseodymium', '140.91', 'lanthanide', 3, 6, 'solid', 'Magnets, welder\'s goggles (green glass), aircraft alloys.'],
  [60, 'Nd', 'Neodymium', '144.24', 'lanthanide', 3, 6, 'solid', 'The strongest permanent magnets — in every hard drive, motor and headphone.'],
  [61, 'Pm', 'Promethium', '[145]', 'lanthanide', 3, 6, 'solid', 'Radioactive, no stable form; luminous paint, nuclear batteries.'],
  [62, 'Sm', 'Samarium', '150.36', 'lanthanide', 3, 6, 'solid', 'Magnets that keep working when hot; cancer treatment.'],
  [63, 'Eu', 'Europium', '151.96', 'lanthanide', 3, 6, 'solid', 'The red in screens; the glow in banknotes under ultraviolet.'],
  [64, 'Gd', 'Gadolinium', '157.25', 'lanthanide', 3, 6, 'solid', 'MRI contrast agent; neutron shielding.'],
  [65, 'Tb', 'Terbium', '158.93', 'lanthanide', 3, 6, 'solid', 'Green phosphors; magnets that change shape in a field.'],
  [66, 'Dy', 'Dysprosium', '162.50', 'lanthanide', 3, 6, 'solid', 'Keeps neodymium magnets strong at high temperature — wind turbines, electric cars.'],
  [67, 'Ho', 'Holmium', '164.93', 'lanthanide', 3, 6, 'solid', 'The most magnetic element; surgical lasers.'],
  [68, 'Er', 'Erbium', '167.26', 'lanthanide', 3, 6, 'solid', 'Amplifies the light in optical fibre; pink glass.'],
  [69, 'Tm', 'Thulium', '168.93', 'lanthanide', 3, 6, 'solid', 'Rarest stable rare earth; portable X-ray sources.'],
  [70, 'Yb', 'Ytterbium', '173.05', 'lanthanide', 3, 6, 'solid', 'Steel alloys, lasers, atomic clocks.'],
  [71, 'Lu', 'Lutetium', '174.97', 'lanthanide', 3, 6, 'solid', 'PET scanners; catalysts in oil refining.'],
  [72, 'Hf', 'Hafnium', '178.49', 'transition', 4, 6, 'solid', 'Control rods in reactors; plasma-cutting tips; chip insulators.'],
  [73, 'Ta', 'Tantalum', '180.95', 'transition', 5, 6, 'solid', 'Capacitors in every phone; surgical implants — the body ignores it.'],
  [74, 'W', 'Tungsten', '183.84', 'transition', 6, 6, 'solid', 'Highest melting point of any metal: light-bulb filaments, cutting tools, armour-piercing shot. Denser than lead.'],
  [75, 'Re', 'Rhenium', '186.21', 'transition', 7, 6, 'solid', 'Jet-engine blades that run white-hot. One of the rarest elements.'],
  [76, 'Os', 'Osmium', '190.23', 'transition', 8, 6, 'solid', 'The densest element. Fountain-pen nibs, electrical contacts. Its oxide is very poisonous.'],
  [77, 'Ir', 'Iridium', '192.22', 'transition', 9, 6, 'solid', 'Most corrosion-resistant metal; spark plugs. A layer of it in the rocks marks the asteroid that ended the dinosaurs.'],
  [78, 'Pt', 'Platinum', '195.08', 'transition', 10, 6, 'solid', 'Precious, inert, a catalyst: converters, fuel cells, lab crucibles, jewellery, cancer drugs.'],
  [79, 'Au', 'Gold', '196.97', 'transition', 11, 6, 'solid', 'Never tarnishes, never rusts; found pure in rivers. Money for five thousand years; the best contacts in electronics; dentistry.'],
  [80, 'Hg', 'Mercury', '200.59', 'transition', 12, 6, 'liquid', 'Liquid metal. Old thermometers, barometers, switches, dental fillings. Poisonous — the vapour especially; never heat it, never touch a spill bare-handed.'],
  [81, 'Tl', 'Thallium', '204.38', 'post', 13, 6, 'solid', 'Very poisonous; once rat poison. Infrared optics.'],
  [82, 'Pb', 'Lead', '207.2', 'post', 14, 6, 'solid', 'Soft, heavy, easy to melt and cast: pipes, roofs, shot, batteries, solder, type. Poisonous, especially to children — never in cookware or water pipes.'],
  [83, 'Bi', 'Bismuth', '208.98', 'post', 15, 6, 'solid', 'Heaviest stable-ish element; iridescent crystals; stomach medicine; lead-free shot and solder.'],
  [84, 'Po', 'Polonium', '[209]', 'post', 16, 6, 'solid', 'Intensely radioactive; static eliminators, spacecraft heaters. Discovered by Marie Curie.'],
  [85, 'At', 'Astatine', '[210]', 'halogen', 17, 6, 'solid', 'Rarest natural element — less than a gram on Earth at any moment.'],
  [86, 'Rn', 'Radon', '[222]', 'noble', 18, 6, 'gas', 'Radioactive gas that seeps from granite into cellars. Ventilate. Second cause of lung cancer after smoking.'],
  [87, 'Fr', 'Francium', '[223]', 'alkali', 1, 7, 'solid', 'Extremely radioactive; a few atoms at a time. Of no use.'],
  [88, 'Ra', 'Radium', '[226]', 'alkaline', 2, 7, 'solid', 'Glowed on old watch dials and poisoned the painters. Discovered by the Curies.'],
  [89, 'Ac', 'Actinium', '[227]', 'actinide', 3, 7, 'solid', 'Radioactive; glows blue in the dark; cancer therapy.'],
  [90, 'Th', 'Thorium', '232.04', 'actinide', 3, 7, 'solid', 'Mildly radioactive; gas-mantle glow, and a possible reactor fuel more plentiful than uranium.'],
  [91, 'Pa', 'Protactinium', '231.04', 'actinide', 3, 7, 'solid', 'Rare, radioactive, toxic; a scientific curiosity.'],
  [92, 'U', 'Uranium', '238.03', 'actinide', 3, 7, 'solid', 'Nuclear fuel and bombs (the rare isotope 235). Mildly radioactive as a metal; heavy, once used for yellow glass and tank armour.'],
  [93, 'Np', 'Neptunium', '[237]', 'actinide', 3, 7, 'solid', 'Made in reactors; a by-product of plutonium production.'],
  [94, 'Pu', 'Plutonium', '[244]', 'actinide', 3, 7, 'solid', 'Bomb cores and reactor fuel; the heat source in deep-space probes. Made from uranium.'],
  [95, 'Am', 'Americium', '[243]', 'actinide', 3, 7, 'solid', 'The speck inside most smoke detectors.'],
  [96, 'Cm', 'Curium', '[247]', 'actinide', 3, 7, 'solid', 'Power for spacecraft instruments; rock analysers on Mars rovers.'],
  [97, 'Bk', 'Berkelium', '[247]', 'actinide', 3, 7, 'solid', 'Made a few milligrams at a time for research.'],
  [98, 'Cf', 'Californium', '[251]', 'actinide', 3, 7, 'solid', 'A neutron source for starting reactors and finding gold and oil.'],
  [99, 'Es', 'Einsteinium', '[252]', 'actinide', 3, 7, 'solid', 'First found in the debris of a hydrogen bomb.'],
  [100, 'Fm', 'Fermium', '[257]', 'actinide', 3, 7, 'solid', 'Research only.'],
  [101, 'Md', 'Mendelevium', '[258]', 'actinide', 3, 7, 'solid', 'Named for the man who drew this table.'],
  [102, 'No', 'Nobelium', '[259]', 'actinide', 3, 7, 'solid', 'Research only.'],
  [103, 'Lr', 'Lawrencium', '[266]', 'actinide', 3, 7, 'solid', 'Research only.'],
  [104, 'Rf', 'Rutherfordium', '[267]', 'transition', 4, 7, 'solid', 'A few atoms, lasting seconds.'],
  [105, 'Db', 'Dubnium', '[268]', 'transition', 5, 7, 'solid', 'A few atoms, lasting seconds.'],
  [106, 'Sg', 'Seaborgium', '[269]', 'transition', 6, 7, 'solid', 'A few atoms, lasting seconds.'],
  [107, 'Bh', 'Bohrium', '[270]', 'transition', 7, 7, 'solid', 'A few atoms, lasting seconds.'],
  [108, 'Hs', 'Hassium', '[269]', 'transition', 8, 7, 'solid', 'A few atoms, lasting seconds.'],
  [109, 'Mt', 'Meitnerium', '[278]', 'unknown', 9, 7, 'solid', 'A few atoms, lasting seconds.'],
  [110, 'Ds', 'Darmstadtium', '[281]', 'unknown', 10, 7, 'solid', 'A few atoms, lasting seconds.'],
  [111, 'Rg', 'Roentgenium', '[282]', 'unknown', 11, 7, 'solid', 'A few atoms, lasting seconds.'],
  [112, 'Cn', 'Copernicium', '[285]', 'transition', 12, 7, 'solid', 'A few atoms; may be a gas or liquid at room temperature.'],
  [113, 'Nh', 'Nihonium', '[286]', 'unknown', 13, 7, 'solid', 'Discovered in Japan; a few atoms.'],
  [114, 'Fl', 'Flerovium', '[289]', 'unknown', 14, 7, 'solid', 'A few atoms.'],
  [115, 'Mc', 'Moscovium', '[290]', 'unknown', 15, 7, 'solid', 'A few atoms.'],
  [116, 'Lv', 'Livermorium', '[293]', 'unknown', 16, 7, 'solid', 'A few atoms.'],
  [117, 'Ts', 'Tennessine', '[294]', 'unknown', 17, 7, 'solid', 'A few atoms.'],
  [118, 'Og', 'Oganesson', '[294]', 'unknown', 18, 7, 'solid', 'The heaviest element made so far; five atoms, ever.'],
];

window.vaultElements = { ELEMENTS, ELEMENT_CATEGORIES };
